"""Curated SI formula catalog for the Formulas application."""


ANY = "any"
POSITIVE = "positive"
NONNEGATIVE = "nonnegative"

PI = 3.141592653589793
STANDARD_GRAVITY = 9.80665
GAS_CONSTANT = 8.314462618
LIGHT_SPEED = 299792458.0
PLANCK_CONSTANT = 6.62607015e-34
GRAVITATIONAL_CONSTANT = 6.67430e-11
EARTH_RADIUS = 6371000.0


def variable(key, label, unit, rule=POSITIVE):
    return (key, label, unit, rule)


def formula(identifier, path, title, expression, variables, solvers,
            example, note, constants=None):
    return {
        "id": identifier,
        "path": path,
        "title": title,
        "expression": expression,
        "variables": variables,
        "solvers": solvers,
        "constants": constants or {},
        "example": example,
        "note": note,
    }


FORMULAS = (
    formula(
        "rectangle-area", ("Mathematics", "Geometry"), "Rectangle area",
        "A = l w",
        (variable("A", "Area", "m^2", NONNEGATIVE),
         variable("l", "Length", "m"),
         variable("w", "Width", "m")),
        {"A": "l w", "l": "A / w", "w": "A / l"},
        {"A": 12.0, "l": 3.0, "w": 4.0},
        "Area of a rectangle with perpendicular sides.",
    ),
    formula(
        "circle-area", ("Mathematics", "Geometry"), "Circle area",
        r"A = pi r^2",
        (variable("A", "Area", "m^2", NONNEGATIVE),
         variable("r", "Radius", "m", NONNEGATIVE)),
        {"A": "pi r^2", "r": r"\sqrt{A / pi}"},
        {"A": PI * 4.0, "r": 2.0},
        "Area enclosed by a circle.",
    ),
    formula(
        "pythagorean", ("Mathematics", "Geometry"), "Pythagorean theorem",
        r"c^2 = a^2 + b^2",
        (variable("a", "Leg a", "m", NONNEGATIVE),
         variable("b", "Leg b", "m", NONNEGATIVE),
         variable("c", "Hypotenuse", "m", NONNEGATIVE)),
        {"a": r"\sqrt{c^2 - b^2}",
         "b": r"\sqrt{c^2 - a^2}",
         "c": r"\sqrt{a^2 + b^2}"},
        {"a": 3.0, "b": 4.0, "c": 5.0},
        "Right triangles only; c is opposite the right angle.",
    ),
    formula(
        "cylinder-volume", ("Mathematics", "Geometry"), "Cylinder volume",
        r"V = pi r^2 h",
        (variable("V", "Volume", "m^3", NONNEGATIVE),
         variable("r", "Radius", "m", NONNEGATIVE),
         variable("h", "Height", "m", NONNEGATIVE)),
        {"V": "pi r^2 h", "r": r"\sqrt{V / (pi h)}",
         "h": "V / (pi r^2)"},
        {"V": PI * 12.0, "r": 2.0, "h": 3.0},
        "Volume of a right circular cylinder.",
    ),
    formula(
        "speed", ("Mechanics", "Motion"), "Speed",
        r"v = \frac{d}{t}",
        (variable("v", "Speed", "m/s", NONNEGATIVE),
         variable("d", "Distance", "m", NONNEGATIVE),
         variable("t", "Time", "s")),
        {"v": "d / t", "d": "v t", "t": "d / v"},
        {"v": 5.0, "d": 100.0, "t": 20.0},
        "Average speed over a measured distance and time.",
    ),
    formula(
        "acceleration", ("Mechanics", "Motion"), "Acceleration",
        r"a = \frac{dv}{t}",
        (variable("a", "Acceleration", "m/s^2", ANY),
         variable("dv", "Velocity change", "m/s", ANY),
         variable("t", "Time", "s")),
        {"a": "dv / t", "dv": "a t", "t": "dv / a"},
        {"a": 5.0, "dv": 10.0, "t": 2.0},
        "Constant average acceleration; signs follow one chosen axis.",
    ),
    formula(
        "newton-force", ("Mechanics", "Forces"), "Newton's second law",
        "F = m a",
        (variable("F", "Net force", "N", ANY),
         variable("m", "Mass", "kg"),
         variable("a", "Acceleration", "m/s^2", ANY)),
        {"F": "m a", "m": "F / a", "a": "F / m"},
        {"F": 6.0, "m": 2.0, "a": 3.0},
        "One-dimensional form; F is the net external force.",
    ),
    formula(
        "momentum", ("Mechanics", "Forces"), "Momentum",
        "p = m v",
        (variable("p", "Momentum", "kg*m/s", ANY),
         variable("m", "Mass", "kg"),
         variable("v", "Velocity", "m/s", ANY)),
        {"p": "m v", "m": "p / v", "v": "p / m"},
        {"p": 6.0, "m": 2.0, "v": 3.0},
        "One-dimensional classical momentum.",
    ),
    formula(
        "kinetic-energy", ("Mechanics", "Energy"), "Kinetic energy",
        r"E_k = \frac{m v^2}{2}",
        (variable("E_k", "Kinetic energy", "J", NONNEGATIVE),
         variable("m", "Mass", "kg"),
         variable("v", "Speed", "m/s", NONNEGATIVE)),
        {"E_k": "m v^2 / 2", "m": "2 E_k / v^2",
         "v": r"\sqrt{2 E_k / m}"},
        {"E_k": 9.0, "m": 2.0, "v": 3.0},
        "Classical, non-relativistic energy; v is speed.",
    ),
    formula(
        "potential-energy", ("Mechanics", "Energy"),
        "Gravitational potential",
        "E_p = m g h",
        (variable("E_p", "Potential energy", "J", ANY),
         variable("m", "Mass", "kg"),
         variable("h", "Height change", "m", ANY)),
        {"E_p": "m g h", "m": "E_p / (g h)",
         "h": "E_p / (m g)"},
        {"E_p": 2.0 * STANDARD_GRAVITY * 3.0, "m": 2.0, "h": 3.0},
        "Near Earth's surface; g = 9.80665 m/s^2.",
        {"g": STANDARD_GRAVITY},
    ),
    formula(
        "work", ("Mechanics", "Energy"), "Mechanical work",
        "W = F d",
        (variable("W", "Work", "J", ANY),
         variable("F", "Force", "N", ANY),
         variable("d", "Displacement", "m", ANY)),
        {"W": "F d", "F": "W / d", "d": "W / F"},
        {"W": 20.0, "F": 5.0, "d": 4.0},
        "Force is constant and parallel to the displacement.",
    ),
    formula(
        "mechanical-power", ("Mechanics", "Energy"), "Power",
        r"P = \frac{W}{t}",
        (variable("P", "Power", "W", ANY),
         variable("W", "Work or energy", "J", ANY),
         variable("t", "Time", "s")),
        {"P": "W / t", "W": "P t", "t": "W / P"},
        {"P": 5.0, "W": 100.0, "t": 20.0},
        "Average power over the stated time interval.",
    ),
    formula(
        "density", ("Matter and fluids",), "Density",
        r"\rho = \frac{m}{V}",
        (variable("rho", "Density", "kg/m^3", NONNEGATIVE),
         variable("m", "Mass", "kg", NONNEGATIVE),
         variable("V", "Volume", "m^3")),
        {"rho": "m / V", "m": "rho V", "V": "m / rho"},
        {"rho": 4.0, "m": 8.0, "V": 2.0},
        "Uniform average mass density.",
    ),
    formula(
        "pressure", ("Matter and fluids",), "Pressure",
        r"p = \frac{F}{A}",
        (variable("p", "Pressure", "Pa", ANY),
         variable("F", "Normal force", "N", ANY),
         variable("A", "Area", "m^2")),
        {"p": "F / A", "F": "p A", "A": "F / p"},
        {"p": 50.0, "F": 100.0, "A": 2.0},
        "Uniform normal force over an area.",
    ),
    formula(
        "hydrostatic-pressure", ("Matter and fluids",),
        "Hydrostatic pressure",
        r"p = \rho g h",
        (variable("p", "Gauge pressure", "Pa", NONNEGATIVE),
         variable("rho", "Fluid density", "kg/m^3"),
         variable("h", "Depth", "m", NONNEGATIVE)),
        {"p": "rho g h", "rho": "p / (g h)",
         "h": "p / (rho g)"},
        {"p": 1000.0 * STANDARD_GRAVITY * 2.0,
         "rho": 1000.0, "h": 2.0},
        "Static fluid under standard Earth gravity.",
        {"g": STANDARD_GRAVITY},
    ),
    formula(
        "buoyant-force", ("Matter and fluids",), "Buoyant force",
        r"F_b = \rho V g",
        (variable("F_b", "Buoyant force", "N", NONNEGATIVE),
         variable("rho", "Fluid density", "kg/m^3"),
         variable("V", "Displaced volume", "m^3", NONNEGATIVE)),
        {"F_b": "rho V g", "rho": "F_b / (V g)",
         "V": "F_b / (rho g)"},
        {"F_b": 1000.0 * 0.01 * STANDARD_GRAVITY,
         "rho": 1000.0, "V": 0.01},
        "Archimedes' principle under standard Earth gravity.",
        {"g": STANDARD_GRAVITY},
    ),
    formula(
        "volume-flow", ("Matter and fluids",), "Volume flow rate",
        r"q = \frac{V}{t}",
        (variable("q", "Flow rate", "m^3/s", ANY),
         variable("V", "Fluid volume", "m^3", ANY),
         variable("t", "Time", "s")),
        {"q": "V / t", "V": "q t", "t": "V / q"},
        {"q": 5.0, "V": 10.0, "t": 2.0},
        "Average volumetric flow over the stated interval.",
    ),
    formula(
        "sensible-heat", ("Thermodynamics",), "Sensible heat",
        "Q = m c dT",
        (variable("Q", "Heat energy", "J", ANY),
         variable("m", "Mass", "kg"),
         variable("c", "Specific heat", "J/(kg*K)"),
         variable("dT", "Temperature change", "K", ANY)),
        {"Q": "m c dT", "m": "Q / (c dT)",
         "c": "Q / (m dT)", "dT": "Q / (m c)"},
        {"Q": 3000.0, "m": 2.0, "c": 500.0, "dT": 3.0},
        "No phase change; specific heat is treated as constant.",
    ),
    formula(
        "ideal-gas", ("Thermodynamics",), "Ideal gas law",
        "p V = n R T",
        (variable("p", "Absolute pressure", "Pa"),
         variable("V", "Volume", "m^3"),
         variable("n", "Amount", "mol"),
         variable("T", "Absolute temperature", "K")),
        {"p": "n R T / V", "V": "n R T / p",
         "n": "p V / (R T)", "T": "p V / (n R)"},
        {"p": 2.0 * GAS_CONSTANT * 300.0 / 0.1,
         "V": 0.1, "n": 2.0, "T": 300.0},
        "Ideal gas approximation; R = 8.314462618 J/(mol*K).",
        {"R": GAS_CONSTANT},
    ),
    formula(
        "linear-expansion", ("Thermodynamics",), "Linear expansion",
        "dL = alpha L dT",
        (variable("dL", "Length change", "m", ANY),
         variable("alpha", "Expansion coefficient", "1/K", ANY),
         variable("L", "Initial length", "m"),
         variable("dT", "Temperature change", "K", ANY)),
        {"dL": "alpha L dT", "alpha": "dL / (L dT)",
         "L": "dL / (alpha dT)", "dT": "dL / (alpha L)"},
        {"dL": 0.001, "alpha": 0.00001, "L": 2.0, "dT": 50.0},
        "Small thermal changes with constant expansion coefficient.",
    ),
    formula(
        "ohms-law", ("Electricity", "Circuits"), "Ohm's law",
        "V = I R",
        (variable("V", "Voltage", "V", ANY),
         variable("I", "Current", "A", ANY),
         variable("R", "Resistance", "ohm")),
        {"V": "I R", "I": "V / R", "R": "V / I"},
        {"V": 10.0, "I": 2.0, "R": 5.0},
        "DC or instantaneous values for an ohmic element.",
    ),
    formula(
        "electric-power", ("Electricity", "Circuits"), "Electric power",
        "P = V I",
        (variable("P", "Power", "W", ANY),
         variable("V", "Voltage", "V", ANY),
         variable("I", "Current", "A", ANY)),
        {"P": "V I", "V": "P / I", "I": "P / V"},
        {"P": 20.0, "V": 10.0, "I": 2.0},
        "DC power; signs follow the passive sign convention.",
    ),
    formula(
        "electric-energy", ("Electricity", "Circuits"), "Electric energy",
        "E = P t",
        (variable("E", "Energy", "J", ANY),
         variable("P", "Power", "W", ANY),
         variable("t", "Time", "s")),
        {"E": "P t", "P": "E / t", "t": "E / P"},
        {"E": 200.0, "P": 20.0, "t": 10.0},
        "Constant or average electrical power.",
    ),
    formula(
        "electric-charge", ("Electricity", "Circuits"), "Electric charge",
        "Q = I t",
        (variable("Q", "Charge", "C", ANY),
         variable("I", "Current", "A", ANY),
         variable("t", "Time", "s")),
        {"Q": "I t", "I": "Q / t", "t": "Q / I"},
        {"Q": 6.0, "I": 2.0, "t": 3.0},
        "Constant or average current over time.",
    ),
    formula(
        "series-resistance", ("Electricity", "Circuits"),
        "Series resistance",
        "R = R_1 + R_2",
        (variable("R", "Equivalent resistance", "ohm"),
         variable("R_1", "Resistance 1", "ohm"),
         variable("R_2", "Resistance 2", "ohm")),
        {"R": "R_1 + R_2", "R_1": "R - R_2", "R_2": "R - R_1"},
        {"R": 5.0, "R_1": 2.0, "R_2": 3.0},
        "Two resistors in series.",
    ),
    formula(
        "parallel-resistance", ("Electricity", "Circuits"),
        "Parallel resistance",
        r"R = \frac{R_1 R_2}{R_1 + R_2}",
        (variable("R", "Equivalent resistance", "ohm"),
         variable("R_1", "Resistance 1", "ohm"),
         variable("R_2", "Resistance 2", "ohm")),
        {"R": "R_1 R_2 / (R_1 + R_2)",
         "R_1": "R R_2 / (R_2 - R)",
         "R_2": "R R_1 / (R_1 - R)"},
        {"R": 2.0, "R_1": 6.0, "R_2": 3.0},
        "Two positive resistors in parallel; R is smaller than either.",
    ),
    formula(
        "capacitor-charge", ("Electricity", "Circuits"),
        "Capacitor charge",
        "Q = C V",
        (variable("Q", "Charge", "C", ANY),
         variable("C", "Capacitance", "F"),
         variable("V", "Voltage", "V", ANY)),
        {"Q": "C V", "C": "Q / V", "V": "Q / C"},
        {"Q": 0.12, "C": 0.01, "V": 12.0},
        "Charge on an ideal capacitor.",
    ),
    formula(
        "wave-speed", ("Waves and radio",), "Wave speed",
        r"v = f \lambda",
        (variable("v", "Wave speed", "m/s", NONNEGATIVE),
         variable("f", "Frequency", "Hz"),
         variable("lambda", "Wavelength", "m")),
        {"v": "f lambda", "f": "v / lambda", "lambda": "v / f"},
        {"v": 10.0, "f": 5.0, "lambda": 2.0},
        "Phase speed, frequency, and wavelength in one medium.",
    ),
    formula(
        "period-frequency", ("Waves and radio",), "Period and frequency",
        r"T = \frac{1}{f}",
        (variable("T", "Period", "s"),
         variable("f", "Frequency", "Hz")),
        {"T": "1 / f", "f": "1 / T"},
        {"T": 0.25, "f": 4.0},
        "Period is the duration of one cycle.",
    ),
    formula(
        "photon-energy", ("Waves and radio",), "Photon energy",
        "E = h f",
        (variable("E", "Photon energy", "J", NONNEGATIVE),
         variable("f", "Frequency", "Hz")),
        {"E": "h f", "f": "E / h"},
        {"E": PLANCK_CONSTANT * 1000000.0, "f": 1000000.0},
        "Planck relation; h = 6.62607015e-34 J*s.",
        {"h": PLANCK_CONSTANT},
    ),
    formula(
        "radio-wavelength", ("Waves and radio",),
        "Free-space wavelength",
        r"\lambda = \frac{c}{f}",
        (variable("lambda", "Wavelength", "m"),
         variable("f", "Frequency", "Hz")),
        {"lambda": "c / f", "f": "c / lambda"},
        {"lambda": LIGHT_SPEED / 100000000.0, "f": 100000000.0},
        "Vacuum approximation; c = 299792458 m/s.",
        {"c": LIGHT_SPEED},
    ),
    formula(
        "isotropic-intensity", ("Waves and radio",),
        "Isotropic intensity",
        r"I = \frac{P}{4 pi r^2}",
        (variable("I", "Intensity", "W/m^2", NONNEGATIVE),
         variable("P", "Radiated power", "W", NONNEGATIVE),
         variable("r", "Distance", "m")),
        {"I": "P / (4 pi r^2)", "P": "4 pi r^2 I",
         "r": r"\sqrt{P / (4 pi I)}"},
        {"I": 100.0 / (16.0 * PI), "P": 100.0, "r": 2.0},
        "Uniform radiation into free space with no losses.",
    ),
    formula(
        "amount-of-substance", ("Chemistry",), "Amount of substance",
        r"n = \frac{m}{M}",
        (variable("n", "Amount", "mol", NONNEGATIVE),
         variable("m", "Mass", "kg", NONNEGATIVE),
         variable("M", "Molar mass", "kg/mol")),
        {"n": "m / M", "m": "n M", "M": "m / n"},
        {"n": 1.0, "m": 0.018, "M": 0.018},
        "Mass and molar mass must use coherent SI units.",
    ),
    formula(
        "molar-concentration", ("Chemistry",), "Molar concentration",
        r"c = \frac{n}{V}",
        (variable("c", "Concentration", "mol/m^3", NONNEGATIVE),
         variable("n", "Amount", "mol", NONNEGATIVE),
         variable("V", "Solution volume", "m^3")),
        {"c": "n / V", "n": "c V", "V": "n / c"},
        {"c": 4.0, "n": 2.0, "V": 0.5},
        "Amount concentration in coherent SI units.",
    ),
    formula(
        "dilution", ("Chemistry",), "Dilution",
        "c_1 V_1 = c_2 V_2",
        (variable("c_1", "Initial concentration", "mol/m^3"),
         variable("V_1", "Initial volume", "m^3"),
         variable("c_2", "Final concentration", "mol/m^3"),
         variable("V_2", "Final volume", "m^3")),
        {"c_1": "c_2 V_2 / V_1", "V_1": "c_2 V_2 / c_1",
         "c_2": "c_1 V_1 / V_2", "V_2": "c_1 V_1 / c_2"},
        {"c_1": 2.0, "V_1": 3.0, "c_2": 1.5, "V_2": 4.0},
        "Solute amount is conserved; volumes are treated as additive.",
    ),
    formula(
        "horizon-distance", ("Navigation and space",),
        "Geometric horizon",
        r"d = \sqrt{2 R h + h^2}",
        (variable("d", "Line-of-sight distance", "m", NONNEGATIVE),
         variable("h", "Observer height", "m", NONNEGATIVE)),
        {"d": r"\sqrt{2 R h + h^2}",
         "h": r"\sqrt{R^2 + d^2} - R"},
        {"d": (2.0 * EARTH_RADIUS * 2.0 + 4.0) ** 0.5, "h": 2.0},
        "Spherical Earth, no refraction; R = 6371000 m.",
        {"R": EARTH_RADIUS},
    ),
    formula(
        "universal-gravity", ("Navigation and space",),
        "Universal gravitation",
        r"F = \frac{G m_1 m_2}{r^2}",
        (variable("F", "Force magnitude", "N", NONNEGATIVE),
         variable("m_1", "Mass 1", "kg"),
         variable("m_2", "Mass 2", "kg"),
         variable("r", "Center distance", "m")),
        {"F": "G m_1 m_2 / r^2", "m_1": "F r^2 / (G m_2)",
         "m_2": "F r^2 / (G m_1)",
         "r": r"\sqrt{G m_1 m_2 / F}"},
        {"F": GRAVITATIONAL_CONSTANT * 5.0 * 10.0 / 4.0,
         "m_1": 5.0, "m_2": 10.0, "r": 2.0},
        "Point masses; G = 6.67430e-11 m^3/(kg*s^2).",
        {"G": GRAVITATIONAL_CONSTANT},
    ),
    formula(
        "circular-orbit-speed", ("Navigation and space",),
        "Circular orbit speed",
        r"v = \sqrt{\frac{G M}{r}}",
        (variable("v", "Orbital speed", "m/s", NONNEGATIVE),
         variable("M", "Central mass", "kg"),
         variable("r", "Orbital radius", "m")),
        {"v": r"\sqrt{G M / r}", "M": "v^2 r / G",
         "r": "G M / v^2"},
        {"v": (GRAVITATIONAL_CONSTANT * 5.9722e24 / 6371000.0) ** 0.5,
         "M": 5.9722e24, "r": 6371000.0},
        "Circular two-body orbit; r is measured from the center.",
        {"G": GRAVITATIONAL_CONSTANT},
    ),
)
